// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SME.VHDL.Templates {
    using System.Linq;
    using SME;
    using System.Text;
    using System.Collections.Generic;
    using SME.VHDL;
    using SME.AST;
    using System;
    
    
    public partial class Entity : EntityBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 9 ""
            this.Write("library IEEE;\nuse IEEE.STD_LOGIC_1164.ALL;\nuse IEEE.NUMERIC_STD.ALL;\n\n-- library SYSTEM_TYPES;\nuse work.SYSTEM_TYPES.ALL;\n\n-- library CUSTOM_TYPES;\nuse work.CUSTOM_TYPES.ALL;\n\n-- User defined packages here\n-- #### USER-DATA-IMPORTS-START\n-- #### USER-DATA-IMPORTS-END\n\n\nentity ");
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Process.Name ));
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write(" is\n  port(\n");
            
            #line default
            #line hidden
            
            #line 26 ""
 foreach (var bus in Process.InputBusses.Where(x => !Process.OutputBusses.Contains(x))) { 
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write("    -- Input bus ");
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write(" signals\n");
            
            #line default
            #line hidden
            
            #line 28 ""
     foreach (var signal in bus.Signals) { 
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( signal.Name ));
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write(": in ");
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 30 ""
     } 
            
            #line default
            #line hidden
            
            #line 31 ""
 } 
            
            #line default
            #line hidden
            
            #line 32 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 33 ""
 foreach (var bus in Process.OutputBusses.Where(x => !Process.InputBusses.Contains(x))) { 
            
            #line default
            #line hidden
            
            #line 34 ""
            this.Write("    -- Output bus ");
            
            #line default
            #line hidden
            
            #line 34 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 34 ""
            this.Write(" signals\n");
            
            #line default
            #line hidden
            
            #line 35 ""
     foreach (var signal in RSP.WrittenSignals(bus)) { 
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( signal.Name ));
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write(": out ");
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 37 ""
     } 
            
            #line default
            #line hidden
            
            #line 38 ""
 } 
            
            #line default
            #line hidden
            
            #line 39 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 40 ""
 foreach (var bus in Process.InputBusses.Where(x => Process.OutputBusses.Contains(x))) { 
            
            #line default
            #line hidden
            
            #line 41 ""
            this.Write("    -- Input/output bus ");
            
            #line default
            #line hidden
            
            #line 41 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 41 ""
            this.Write(" signals\n");
            
            #line default
            #line hidden
            
            #line 42 ""
     foreach (var signal in bus.Signals) { 
            
            #line default
            #line hidden
            
            #line 43 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 43 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 43 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 43 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( signal.Name ));
            
            #line default
            #line hidden
            
            #line 43 ""
            this.Write(": in ");
            
            #line default
            #line hidden
            
            #line 43 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 43 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 44 ""
     } 
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 46 ""
     foreach (var signal in bus.Signals) { 
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write("    out_");
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( signal.Name ));
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write(": out ");
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 48 ""
     } 
            
            #line default
            #line hidden
            
            #line 49 ""
 } 
            
            #line default
            #line hidden
            
            #line 50 ""
            this.Write("\n    -- Reset signal\n    RST : Std_logic;\n\n    -- Clock signal\n    CLK : Std_logic\n );\nend ");
            
            #line default
            #line hidden
            
            #line 57 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Process.Name ));
            
            #line default
            #line hidden
            
            #line 57 ""
            this.Write(";\n\narchitecture RTL of ");
            
            #line default
            #line hidden
            
            #line 59 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Process.Name ));
            
            #line default
            #line hidden
            
            #line 59 ""
            this.Write(" is\n");
            
            #line default
            #line hidden
            
            #line 60 ""
 if (RSP.TypeDefinitions.Count() > 0) { 
            
            #line default
            #line hidden
            
            #line 61 ""
            this.Write("\n   -- Type definitions\n");
            
            #line default
            #line hidden
            
            #line 63 ""
 } 
            
            #line default
            #line hidden
            
            #line 64 ""
 foreach (var t in RSP.TypeDefinitions) { 
            
            #line default
            #line hidden
            
            #line 65 ""
            this.Write("  ");
            
            #line default
            #line hidden
            
            #line 65 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( t ));
            
            #line default
            #line hidden
            
            #line 65 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 66 ""
 } 
            
            #line default
            #line hidden
            
            #line 67 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 68 ""
 foreach (var bus in Process.InternalBusses) { 
            
            #line default
            #line hidden
            
            #line 69 ""
            this.Write("  -- Internal bus ");
            
            #line default
            #line hidden
            
            #line 69 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 69 ""
            this.Write(" signals\n");
            
            #line default
            #line hidden
            
            #line 70 ""
     foreach (var signal in bus.Signals) { 
            
            #line default
            #line hidden
            
            #line 71 ""
         if (Process.IsClocked) { 
            
            #line default
            #line hidden
            
            #line 72 ""
            this.Write("  signal ");
            
            #line default
            #line hidden
            
            #line 72 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 72 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 72 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( signal.Name ));
            
            #line default
            #line hidden
            
            #line 72 ""
            this.Write(": ");
            
            #line default
            #line hidden
            
            #line 72 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 72 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 73 ""
         } else { 
            
            #line default
            #line hidden
            
            #line 74 ""
            this.Write("  signal ");
            
            #line default
            #line hidden
            
            #line 74 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 74 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 74 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( signal.Name ));
            
            #line default
            #line hidden
            
            #line 74 ""
            this.Write(", next_");
            
            #line default
            #line hidden
            
            #line 74 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 74 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 74 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( signal.Name ));
            
            #line default
            #line hidden
            
            #line 74 ""
            this.Write(": ");
            
            #line default
            #line hidden
            
            #line 74 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 74 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 75 ""
         } 
            
            #line default
            #line hidden
            
            #line 76 ""
     } 
            
            #line default
            #line hidden
            
            #line 77 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 78 ""
 } 
            
            #line default
            #line hidden
            
            #line 79 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 80 ""
 if (Process.SharedSignals.Any()) { 
            
            #line default
            #line hidden
            
            #line 81 ""
            this.Write("  -- Internal signals\n");
            
            #line default
            #line hidden
            
            #line 82 ""
 } 
            
            #line default
            #line hidden
            
            #line 83 ""
 foreach (var s in Process.SharedSignals) { 
            
            #line default
            #line hidden
            
            #line 84 ""
            this.Write("  signal ");
            
            #line default
            #line hidden
            
            #line 84 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( s.Name ));
            
            #line default
            #line hidden
            
            #line 84 ""
            this.Write(" : ");
            
            #line default
            #line hidden
            
            #line 84 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(s) ));
            
            #line default
            #line hidden
            
            #line 84 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 85 ""
 } 
            
            #line default
            #line hidden
            
            #line 86 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 87 ""
 if (RSP.IsComponent) { 
            
            #line default
            #line hidden
            
            #line 88 ""
            this.Write("  -- Component declaration and signals\n");
            
            #line default
            #line hidden
            
            #line 89 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RSP.ComponentSignals ));
            
            #line default
            #line hidden
            
            #line 89 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 90 ""
 } 
            
            #line default
            #line hidden
            
            #line 91 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 92 ""
 if (Process.Methods != null && Process.Methods.Any(x => !x.Ignore)) { 
            
            #line default
            #line hidden
            
            #line 93 ""
            this.Write("  -- Internal methods\n");
            
            #line default
            #line hidden
            
            #line 94 ""
     foreach (var s in Process.Methods.Where(x => !x.Ignore)) { 
            
            #line default
            #line hidden
            
            #line 95 ""
         foreach(var line in RSP.RenderMethod(s)) { 
            
            #line default
            #line hidden
            
            #line 96 ""
            this.Write("  ");
            
            #line default
            #line hidden
            
            #line 96 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( line ));
            
            #line default
            #line hidden
            
            #line 96 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 97 ""
         } 
            
            #line default
            #line hidden
            
            #line 98 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 99 ""
     } 
            
            #line default
            #line hidden
            
            #line 100 ""
 } 
            
            #line default
            #line hidden
            
            #line 101 ""
            this.Write("\n\n  -- User defined signals, procedures and components here\n  -- #### USER-DATA-SIGNALS-START\n  -- #### USER-DATA-SIGNALS-END\n\nbegin\n\n    -- #### USER-DATA-PROCESSES-START\n    -- #### USER-DATA-PROCESSES-END\n\n");
            
            #line default
            #line hidden
            
            #line 112 ""
 if (RSP.IsComponent) { 
            
            #line default
            #line hidden
            
            #line 113 ""
            this.Write("    -- Component instantiation\n");
            
            #line default
            #line hidden
            
            #line 114 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RSP.ComponentProcesses ));
            
            #line default
            #line hidden
            
            #line 114 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 115 ""
 } else { 
            
            #line default
            #line hidden
            
            #line 116 ""
            this.Write("\n    process(\n");
            
            #line default
            #line hidden
            
            #line 118 ""
     if (Process.IsClocked) { 
            
            #line default
            #line hidden
            
            #line 119 ""
            this.Write("        -- #### USER-DATA-SENSITIVITY-START\n        -- #### USER-DATA-SENSITIVITY-END\n");
            
            #line default
            #line hidden
            
            #line 121 ""
     } 
            
            #line default
            #line hidden
            
            #line 122 ""
            this.Write("        CLK, \n        RST\n    )\n\n");
            
            #line default
            #line hidden
            
            #line 126 ""
     if (Process.IsClocked) { 
            
            #line default
            #line hidden
            
            #line 127 ""
         if (RSP.Variables.Count() > 0) { 
            
            #line default
            #line hidden
            
            #line 128 ""
            this.Write("    -- Internal variables\n");
            
            #line default
            #line hidden
            
            #line 129 ""
             foreach(var s in RSP.Variables) { 
            
            #line default
            #line hidden
            
            #line 130 ""
            this.Write("    variable ");
            
            #line default
            #line hidden
            
            #line 130 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( s.Name ));
            
            #line default
            #line hidden
            
            #line 130 ""
            this.Write(" : ");
            
            #line default
            #line hidden
            
            #line 130 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(s) ));
            
            #line default
            #line hidden
            
            #line 130 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 131 ""
             } 
            
            #line default
            #line hidden
            
            #line 132 ""
         } 
            
            #line default
            #line hidden
            
            #line 133 ""
     } 
            
            #line default
            #line hidden
            
            #line 134 ""
            this.Write("\n    -- #### USER-DATA-CLOCKEDVARIABLES-START\n    -- #### USER-DATA-CLOCKEDVARIABLES-END\n    begin\n\n        -- Shared initialize code here\n        -- #### USER-DATA-CLOCKEDSHAREDINITIALIZECODE-START\n        -- #### USER-DATA-CLOCKEDSHAREDINITIALIZECODE-END\n\n        if RST = '1' then\n");
            
            #line default
            #line hidden
            
            #line 144 ""
     if (Process.IsClocked) { 
            
            #line default
            #line hidden
            
            #line 145 ""
         foreach(var s in RSP.ProcessResetStaments) { 
            
            #line default
            #line hidden
            
            #line 146 ""
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 146 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( s ));
            
            #line default
            #line hidden
            
            #line 146 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 147 ""
         } 
            
            #line default
            #line hidden
            
            #line 148 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 149 ""
     } else { 
            
            #line default
            #line hidden
            
            #line 150 ""
          foreach(var s in RSP.ClockResetStaments) { 
            
            #line default
            #line hidden
            
            #line 151 ""
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 151 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( s.Substring("next_".Length) ));
            
            #line default
            #line hidden
            
            #line 151 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 152 ""
          } 
            
            #line default
            #line hidden
            
            #line 153 ""
     } 
            
            #line default
            #line hidden
            
            #line 154 ""
            this.Write("            -- Reset code here\n            -- #### USER-DATA-RESETCODE-START\n            -- #### USER-DATA-RESETCODE-END\n\n        elsif rising_edge(CLK) then\n\n            -- Initialize code here\n            -- #### USER-DATA-CLOCKEDINITIALIZECODE-START\n            -- #### USER-DATA-CLOCKEDINITIALIZECODE-END\n\n");
            
            #line default
            #line hidden
            
            #line 164 ""
     if (!Process.IsClocked) { 
            
            #line default
            #line hidden
            
            #line 165 ""
         foreach (var bus in Process.InternalBusses) { 
            
            #line default
            #line hidden
            
            #line 166 ""
            this.Write("            -- Propagate internal bus ");
            
            #line default
            #line hidden
            
            #line 166 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 166 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 167 ""
             foreach (var signal in bus.Signals) { 
            
            #line default
            #line hidden
            
            #line 168 ""
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 168 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name));
            
            #line default
            #line hidden
            
            #line 168 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 168 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( signal.Name ));
            
            #line default
            #line hidden
            
            #line 168 ""
            this.Write(" <= next_");
            
            #line default
            #line hidden
            
            #line 168 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 168 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 168 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( signal.Name ));
            
            #line default
            #line hidden
            
            #line 168 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 169 ""
             } 
            
            #line default
            #line hidden
            
            #line 170 ""
         } 
            
            #line default
            #line hidden
            
            #line 171 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 172 ""
     } 
            
            #line default
            #line hidden
            
            #line 173 ""
     if (Process.IsClocked) { 
            
            #line default
            #line hidden
            
            #line 174 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 175 ""
     foreach(var line in RSP.RenderMethod(Process.MainMethod)) { 
            
            #line default
            #line hidden
            
            #line 176 ""
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 176 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( line ));
            
            #line default
            #line hidden
            
            #line 176 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 177 ""
     } 
            
            #line default
            #line hidden
            
            #line 178 ""
            this.Write("\n            -- #### USER-DATA-CODE-START\n            -- #### USER-DATA-CODE-END\n\n");
            
            #line default
            #line hidden
            
            #line 182 ""
     } else { 
            
            #line default
            #line hidden
            
            #line 183 ""
            this.Write("\n            -- #### USER-DATA-ONRISE-START\n            -- #### USER-DATA-ONRISE-END\n\n");
            
            #line default
            #line hidden
            
            #line 187 ""
     } 
            
            #line default
            #line hidden
            
            #line 188 ""
            this.Write("        end if;\n    end process;\n\n");
            
            #line default
            #line hidden
            
            #line 191 ""
     if (!Process.IsClocked) { 
            
            #line default
            #line hidden
            
            #line 192 ""
            this.Write("\n    process(\n        -- #### USER-DATA-SENSITIVITY-START\n        -- #### USER-DATA-SENSITIVITY-END\n");
            
            #line default
            #line hidden
            
            #line 196 ""
         foreach(var signal in Process.InputBusses.Union(Process.InternalBusses).Where(x => !Process.OutputBusses.Contains(x)).SelectMany(x => x.Signals)) { 
            
            #line default
            #line hidden
            
            #line 197 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 197 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( signal.Parent.Name ));
            
            #line default
            #line hidden
            
            #line 197 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 197 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( signal.Name ));
            
            #line default
            #line hidden
            
            #line 197 ""
            this.Write(",\n");
            
            #line default
            #line hidden
            
            #line 198 ""
         } 
            
            #line default
            #line hidden
            
            #line 199 ""
         foreach(var signal in Process.SharedSignals) { 
            
            #line default
            #line hidden
            
            #line 200 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 200 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( signal.Name ));
            
            #line default
            #line hidden
            
            #line 200 ""
            this.Write(",\n");
            
            #line default
            #line hidden
            
            #line 201 ""
         } 
            
            #line default
            #line hidden
            
            #line 202 ""
            this.Write("        CLK,\n        RST\n    )\n");
            
            #line default
            #line hidden
            
            #line 205 ""
         if (RSP.Variables.Count() > 0) { 
            
            #line default
            #line hidden
            
            #line 206 ""
            this.Write("    -- Internal variables\n");
            
            #line default
            #line hidden
            
            #line 207 ""
         } 
            
            #line default
            #line hidden
            
            #line 208 ""
         foreach(var s in RSP.Variables) { 
            
            #line default
            #line hidden
            
            #line 209 ""
            this.Write("    variable ");
            
            #line default
            #line hidden
            
            #line 209 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( s.Name ));
            
            #line default
            #line hidden
            
            #line 209 ""
            this.Write(" : ");
            
            #line default
            #line hidden
            
            #line 209 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(s) ));
            
            #line default
            #line hidden
            
            #line 209 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 210 ""
         } 
            
            #line default
            #line hidden
            
            #line 211 ""
            this.Write("\n    -- #### USER-DATA-NONCLOCKEDVARIABLES-START\n    -- #### USER-DATA-NONCLOCKEDVARIABLES-END\n\tbegin\n        -- Initialize code here\n        -- #### USER-DATA-NONCLOCKEDSHAREDINITIALIZECODE-START\n        -- #### USER-DATA-NONCLOCKEDSHAREDINITIALIZECODE-END\n\n        if RST = '1' then\n");
            
            #line default
            #line hidden
            
            #line 220 ""
     foreach(var s in RSP.ProcessResetStaments) { 
            
            #line default
            #line hidden
            
            #line 221 ""
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 221 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( s ));
            
            #line default
            #line hidden
            
            #line 221 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 222 ""
     } 
            
            #line default
            #line hidden
            
            #line 223 ""
            this.Write("\n            -- Initialize code here\n            -- #### USER-DATA-NONCLOCKEDRESETCODE-START\n            -- #### USER-DATA-NONCLOCKEDRESETCODE-END\n        else\n\n");
            
            #line default
            #line hidden
            
            #line 229 ""
     if (!Process.IsClocked) { 
            
            #line default
            #line hidden
            
            #line 230 ""
         foreach (var bus in Process.InternalBusses) { 
            
            #line default
            #line hidden
            
            #line 231 ""
            this.Write("            -- Initialize internal bus ");
            
            #line default
            #line hidden
            
            #line 231 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 231 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 232 ""
             foreach (var signal in bus.Signals) { 
            
            #line default
            #line hidden
            
            #line 233 ""
            this.Write("            next_");
            
            #line default
            #line hidden
            
            #line 233 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 233 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 233 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( signal.Name ));
            
            #line default
            #line hidden
            
            #line 233 ""
            this.Write(" <= ");
            
            #line default
            #line hidden
            
            #line 233 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( bus.Name ));
            
            #line default
            #line hidden
            
            #line 233 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 233 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( signal.Name ));
            
            #line default
            #line hidden
            
            #line 233 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 234 ""
             } 
            
            #line default
            #line hidden
            
            #line 235 ""
         } 
            
            #line default
            #line hidden
            
            #line 236 ""
     } 
            
            #line default
            #line hidden
            
            #line 237 ""
            this.Write("\n            -- Initialize code here\n            -- #### USER-DATA-NONCLOCKEDINITIALIZECODE-START\n            -- #### USER-DATA-NONCLOCKEDINITIALIZECODE-END\n\n\n");
            
            #line default
            #line hidden
            
            #line 243 ""
     foreach(var line in RSP.RenderMethod(Process.MainMethod)) { 
            
            #line default
            #line hidden
            
            #line 244 ""
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 244 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( line ));
            
            #line default
            #line hidden
            
            #line 244 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 245 ""
     } 
            
            #line default
            #line hidden
            
            #line 246 ""
            this.Write("\n        end if;\n\n        -- Non-clocked process actions here\n\n        -- #### USER-DATA-CODE-START\n        -- #### USER-DATA-CODE-END\n\n    end process;\n\n");
            
            #line default
            #line hidden
            
            #line 256 ""
     } 
            
            #line default
            #line hidden
            
            #line 257 ""
 } 
            
            #line default
            #line hidden
            
            #line 258 ""
            this.Write("end RTL;\n\n-- User defined architectures here\n-- #### USER-DATA-ARCH-START\n-- #### USER-DATA-ARCH-END\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class EntityBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
