//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SME.VHDL.Templates {
    using System.Linq;
    using SME;
    using System.Text;
    using System.Collections.Generic;
    using SME.VHDL;
    using SME.AST;
    using System;
    
    
    public partial class Entity : EntityBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 9 ""
            this.Write("library IEEE;\nuse IEEE.STD_LOGIC_1164.ALL;\nuse IEEE.NUMERIC_STD.ALL;\n\n-- library " +
                    "SYSTEM_TYPES;\nuse work.SYSTEM_TYPES.ALL;\n\n-- library CUSTOM_TYPES;\nuse work.CUST" +
                    "OM_TYPES.ALL;\n\n");
            
            #line default
            #line hidden
            
            #line 19 ""
 if (RSP.HasCustomRenderer) { 
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write("  -- Component declaration and signals\n");
            
            #line default
            #line hidden
            
            #line 21 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RSP.CustomRendererInclude ));
            
            #line default
            #line hidden
            
            #line 21 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 22 ""
 } 
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write("\n-- User defined packages here\n-- #### USER-DATA-IMPORTS-START\n-- #### USER-DATA-" +
                    "IMPORTS-END\n\n\nentity ");
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Process.Name ));
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write(" is\n");
            
            #line default
            #line hidden
            
            #line 30 ""
 var lastel = Process.SharedVariables.Cast<object>().Concat(Process.SharedSignals).LastOrDefault();
   if (lastel != null) {

            
            #line default
            #line hidden
            
            #line 33 ""
            this.Write("  generic(\n");
            
            #line default
            #line hidden
            
            #line 34 ""
     foreach (var variable in Process.SharedVariables) { 
            
            #line default
            #line hidden
            
            #line 35 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 35 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName("reset_" + variable.Name) ));
            
            #line default
            #line hidden
            
            #line 35 ""
            this.Write(": in ");
            
            #line default
            #line hidden
            
            #line 35 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(variable) ));
            
            #line default
            #line hidden
            
            #line 35 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( variable == lastel ? "" : ";" ));
            
            #line default
            #line hidden
            
            #line 35 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 36 ""
     } 
            
            #line default
            #line hidden
            
            #line 37 ""
     foreach (var variable in Process.SharedSignals) { 
            
            #line default
            #line hidden
            
            #line 38 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 38 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName("reset_" + variable.Name) ));
            
            #line default
            #line hidden
            
            #line 38 ""
            this.Write(": in ");
            
            #line default
            #line hidden
            
            #line 38 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(variable) ));
            
            #line default
            #line hidden
            
            #line 38 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( variable == lastel ? "" : ";" ));
            
            #line default
            #line hidden
            
            #line 38 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 39 ""
     } 
            
            #line default
            #line hidden
            
            #line 40 ""
            this.Write("  );\n");
            
            #line default
            #line hidden
            
            #line 41 ""
 } 
            
            #line default
            #line hidden
            
            #line 42 ""
            this.Write("  port(\n");
            
            #line default
            #line hidden
            
            #line 43 ""
 foreach (var bus in Process.InputBusses.Where(x => !Process.OutputBusses.Contains(x))) { 
       var busname = RS.GetLocalBusName(bus, Process);

            
            #line default
            #line hidden
            
            #line 46 ""
            this.Write("    -- Input bus ");
            
            #line default
            #line hidden
            
            #line 46 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( busname ));
            
            #line default
            #line hidden
            
            #line 46 ""
            this.Write(" signals\n");
            
            #line default
            #line hidden
            
            #line 47 ""
     foreach (var signal in bus.Signals) { 
            
            #line default
            #line hidden
            
            #line 48 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 48 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName(busname + "_" + signal.Name) ));
            
            #line default
            #line hidden
            
            #line 48 ""
            this.Write(": in ");
            
            #line default
            #line hidden
            
            #line 48 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 48 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 49 ""
     } 
            
            #line default
            #line hidden
            
            #line 50 ""
 } 
            
            #line default
            #line hidden
            
            #line 51 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 52 ""
 foreach (var bus in Process.OutputBusses.Where(x => !Process.InputBusses.Contains(x))) {
       var busname = RS.GetLocalBusName(bus, Process);

            
            #line default
            #line hidden
            
            #line 55 ""
            this.Write("    -- Output bus ");
            
            #line default
            #line hidden
            
            #line 55 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( busname ));
            
            #line default
            #line hidden
            
            #line 55 ""
            this.Write(" signals\n");
            
            #line default
            #line hidden
            
            #line 56 ""
     foreach (var signal in RSP.WrittenSignals(bus)) { 
            
            #line default
            #line hidden
            
            #line 57 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 57 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName(busname + "_" + signal.Name) ));
            
            #line default
            #line hidden
            
            #line 57 ""
            this.Write(": out ");
            
            #line default
            #line hidden
            
            #line 57 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 57 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 58 ""
     } 
            
            #line default
            #line hidden
            
            #line 59 ""
 } 
            
            #line default
            #line hidden
            
            #line 60 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 61 ""
 foreach (var bus in Process.InputBusses.Where(x => Process.OutputBusses.Contains(x))) {
       var busname = RS.GetLocalBusName(bus, Process);

            
            #line default
            #line hidden
            
            #line 64 ""
            this.Write("    -- Input/output bus ");
            
            #line default
            #line hidden
            
            #line 64 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( busname ));
            
            #line default
            #line hidden
            
            #line 64 ""
            this.Write(" signals\n");
            
            #line default
            #line hidden
            
            #line 65 ""
     foreach (var signal in bus.Signals) { 
            
            #line default
            #line hidden
            
            #line 66 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 66 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName(busname + "_" + signal.Name) ));
            
            #line default
            #line hidden
            
            #line 66 ""
            this.Write(": in ");
            
            #line default
            #line hidden
            
            #line 66 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 66 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 67 ""
     } 
            
            #line default
            #line hidden
            
            #line 68 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 69 ""
     foreach (var signal in bus.Signals) { 
            
            #line default
            #line hidden
            
            #line 70 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 70 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName("out_" + busname + "_" + signal.Name) ));
            
            #line default
            #line hidden
            
            #line 70 ""
            this.Write(": out ");
            
            #line default
            #line hidden
            
            #line 70 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 70 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 71 ""
     } 
            
            #line default
            #line hidden
            
            #line 72 ""
 } 
            
            #line default
            #line hidden
            
            #line 73 ""
            this.Write("\n    -- Clock signal\n    CLK : in Std_logic;\n\n    -- Ready signal\n    RDY : in St" +
                    "d_logic;\n\n    -- Finished signal\n    FIN : out Std_logic;\n\n    -- Enable signal\n" +
                    "    ENB : in Std_logic;\n\n    -- Reset signal\n    RST : in Std_logic\n );\nend ");
            
            #line default
            #line hidden
            
            #line 89 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Process.Name ));
            
            #line default
            #line hidden
            
            #line 89 ""
            this.Write(";\n\narchitecture RTL of ");
            
            #line default
            #line hidden
            
            #line 91 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Process.Name ));
            
            #line default
            #line hidden
            
            #line 91 ""
            this.Write(" is\n");
            
            #line default
            #line hidden
            
            #line 92 ""
 if (RSP.HasCustomRenderer) { 
            
            #line default
            #line hidden
            
            #line 93 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RSP.CustomRendererBody ));
            
            #line default
            #line hidden
            
            #line 93 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 94 ""
 } else { 
            
            #line default
            #line hidden
            
            #line 95 ""
     foreach (var bus in Process.InternalBusses) {
           var busname = RS.GetLocalBusName(bus, Process);

            
            #line default
            #line hidden
            
            #line 98 ""
            this.Write("  -- Internal bus ");
            
            #line default
            #line hidden
            
            #line 98 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( busname ));
            
            #line default
            #line hidden
            
            #line 98 ""
            this.Write(" signals\n");
            
            #line default
            #line hidden
            
            #line 99 ""
         foreach (var signal in bus.Signals) { 
            
            #line default
            #line hidden
            
            #line 100 ""
            this.Write("  signal ");
            
            #line default
            #line hidden
            
            #line 100 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName(busname + "_" + signal.Name) ));
            
            #line default
            #line hidden
            
            #line 100 ""
            this.Write(": ");
            
            #line default
            #line hidden
            
            #line 100 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 100 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 101 ""
         } 
            
            #line default
            #line hidden
            
            #line 102 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 103 ""
     } 
            
            #line default
            #line hidden
            
            #line 104 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 105 ""
     if (Process.SharedSignals.Any()) { 
            
            #line default
            #line hidden
            
            #line 106 ""
            this.Write("  -- Internal signals\n");
            
            #line default
            #line hidden
            
            #line 107 ""
         foreach (var s in Process.SharedSignals) { 
            
            #line default
            #line hidden
            
            #line 108 ""
            this.Write("  signal ");
            
            #line default
            #line hidden
            
            #line 108 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( s.Name ));
            
            #line default
            #line hidden
            
            #line 108 ""
            this.Write(" : ");
            
            #line default
            #line hidden
            
            #line 108 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(s) ));
            
            #line default
            #line hidden
            
            #line 108 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 109 ""
         } 
            
            #line default
            #line hidden
            
            #line 110 ""
 } 
            
            #line default
            #line hidden
            
            #line 111 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 112 ""
     if (Process.Methods != null && Process.Methods.Any(x => !x.Ignore)) { 
            
            #line default
            #line hidden
            
            #line 113 ""
            this.Write("  -- Internal methods\n");
            
            #line default
            #line hidden
            
            #line 114 ""
         foreach (var s in Process.Methods.Where(x => !x.Ignore)) { 
            
            #line default
            #line hidden
            
            #line 115 ""
             foreach(var line in RSP.Helper.RenderMethod(s)) { 
            
            #line default
            #line hidden
            
            #line 116 ""
            this.Write("  ");
            
            #line default
            #line hidden
            
            #line 116 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( line ));
            
            #line default
            #line hidden
            
            #line 116 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 117 ""
             } 
            
            #line default
            #line hidden
            
            #line 118 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 119 ""
         } 
            
            #line default
            #line hidden
            
            #line 120 ""
     } 
            
            #line default
            #line hidden
            
            #line 121 ""
            this.Write("\n  -- User defined signals, procedures and components here\n  -- #### USER-DATA-SI" +
                    "GNALS-START\n  -- #### USER-DATA-SIGNALS-END\n\nbegin\n\n    -- Custom processes go h" +
                    "ere\n    -- #### USER-DATA-PROCESSES-START\n    -- #### USER-DATA-PROCESSES-END\n\n\n" +
                    "");
            
            #line default
            #line hidden
            
            #line 133 ""

var sensitivity_signal = RSP.Process.IsClocked ? "CLK" : "RDY";

            
            #line default
            #line hidden
            
            #line 136 ""
            this.Write("\n    process(\n        -- Custom sensitivity signals here\n        -- #### USER-DAT" +
                    "A-SENSITIVITY-START\n        -- #### USER-DATA-SENSITIVITY-END\n        ");
            
            #line default
            #line hidden
            
            #line 141 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( sensitivity_signal ));
            
            #line default
            #line hidden
            
            #line 141 ""
            this.Write(",\n        RST\n    )\n");
            
            #line default
            #line hidden
            
            #line 144 ""
     if (RSP.Variables.Count() > 0) { 
          var with_reset = Process.SharedVariables;

            
            #line default
            #line hidden
            
            #line 147 ""
            this.Write("    -- Internal variables\n");
            
            #line default
            #line hidden
            
            #line 148 ""
          foreach(var s in RSP.Variables) { 
            
            #line default
            #line hidden
            
            #line 149 ""
            this.Write("    variable ");
            
            #line default
            #line hidden
            
            #line 149 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( s.Name ));
            
            #line default
            #line hidden
            
            #line 149 ""
            this.Write(" : ");
            
            #line default
            #line hidden
            
            #line 149 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(s) ));
            
            #line default
            #line hidden
            
            #line 149 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Process.SharedVariables.Contains(s) ? " := " + Naming.ToValidName("reset_" + s.Name) : "" ));
            
            #line default
            #line hidden
            
            #line 149 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 150 ""
          } 
            
            #line default
            #line hidden
            
            #line 151 ""
     } 
            
            #line default
            #line hidden
            
            #line 152 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 153 ""
     if (!RSP.Process.IsClocked) { 
            
            #line default
            #line hidden
            
            #line 154 ""
            this.Write("    variable reentry_guard: std_logic;\n");
            
            #line default
            #line hidden
            
            #line 155 ""
     } 
            
            #line default
            #line hidden
            
            #line 156 ""
            this.Write(@"
    -- #### USER-DATA-NONCLOCKEDVARIABLES-START
    -- #### USER-DATA-NONCLOCKEDVARIABLES-END
	begin
        -- Initialize code here
        -- #### USER-DATA-NONCLOCKEDSHAREDINITIALIZECODE-START
        -- #### USER-DATA-NONCLOCKEDSHAREDINITIALIZECODE-END

        if RST = '1' then
");
            
            #line default
            #line hidden
            
            #line 165 ""
     foreach(var s in RSP.ProcessResetStaments) { 
            
            #line default
            #line hidden
            
            #line 166 ""
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 166 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( s ));
            
            #line default
            #line hidden
            
            #line 166 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 167 ""
     } 
            
            #line default
            #line hidden
            
            #line 168 ""
     foreach(var variable in Process.SharedVariables) { 
            
            #line default
            #line hidden
            
            #line 169 ""
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 169 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( variable.Name ));
            
            #line default
            #line hidden
            
            #line 169 ""
            this.Write(" := ");
            
            #line default
            #line hidden
            
            #line 169 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName("reset_" + variable.Name) ));
            
            #line default
            #line hidden
            
            #line 169 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 170 ""
     } 
            
            #line default
            #line hidden
            
            #line 171 ""
     foreach(var variable in Process.SharedSignals) { 
            
            #line default
            #line hidden
            
            #line 172 ""
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 172 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( variable.Name ));
            
            #line default
            #line hidden
            
            #line 172 ""
            this.Write(" <= ");
            
            #line default
            #line hidden
            
            #line 172 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName("reset_" + variable.Name) ));
            
            #line default
            #line hidden
            
            #line 172 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 173 ""
     } 
            
            #line default
            #line hidden
            
            #line 174 ""
            this.Write("            \n");
            
            #line default
            #line hidden
            
            #line 175 ""
     if (!RSP.Process.IsClocked) { 
            
            #line default
            #line hidden
            
            #line 176 ""
            this.Write("            reentry_guard := \'0\';\n");
            
            #line default
            #line hidden
            
            #line 177 ""
     } 
            
            #line default
            #line hidden
            
            #line 178 ""
            this.Write("            FIN <= \'0\';\n\n            -- Initialize code here\n            -- #### " +
                    "USER-DATA-NONCLOCKEDRESETCODE-START\n            -- #### USER-DATA-NONCLOCKEDRESE" +
                    "TCODE-END\n\n");
            
            #line default
            #line hidden
            
            #line 184 ""
     if (RSP.Process.IsClocked) { 
            
            #line default
            #line hidden
            
            #line 185 ""
            this.Write("        elsif rising_edge(");
            
            #line default
            #line hidden
            
            #line 185 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( sensitivity_signal ));
            
            #line default
            #line hidden
            
            #line 185 ""
            this.Write(") then\n");
            
            #line default
            #line hidden
            
            #line 186 ""
     } else { 
            
            #line default
            #line hidden
            
            #line 187 ""
            this.Write("        elsif reentry_guard /= RDY then\n            reentry_guard := RDY;\n");
            
            #line default
            #line hidden
            
            #line 189 ""
     } 
            
            #line default
            #line hidden
            
            #line 190 ""
            this.Write("\n            -- Initialize code here\n            -- #### USER-DATA-NONCLOCKEDINIT" +
                    "IALIZECODE-START\n            -- #### USER-DATA-NONCLOCKEDINITIALIZECODE-END\n\n\n");
            
            #line default
            #line hidden
            
            #line 196 ""
     foreach(var line in RSP.Helper.RenderMethod(Process.MainMethod)) { 
            
            #line default
            #line hidden
            
            #line 197 ""
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 197 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( line ));
            
            #line default
            #line hidden
            
            #line 197 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 198 ""
     } 
            
            #line default
            #line hidden
            
            #line 199 ""
            this.Write("\n            FIN <= ");
            
            #line default
            #line hidden
            
            #line 200 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( sensitivity_signal ));
            
            #line default
            #line hidden
            
            #line 200 ""
            this.Write(";\n        end if;\n\n        -- Non-clocked process actions here\n\n        -- #### U" +
                    "SER-DATA-CODE-START\n        -- #### USER-DATA-CODE-END\n\n    end process;\n\n");
            
            #line default
            #line hidden
            
            #line 210 ""
 } 
            
            #line default
            #line hidden
            
            #line 211 ""
            this.Write("\nend RTL;\n\n-- User defined architectures here\n-- #### USER-DATA-ARCH-START\n-- ###" +
                    "# USER-DATA-ARCH-END\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class EntityBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
