//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SME.VHDL.Templates {
    using System.Linq;
    using SME;
    using System.Text;
    using System.Collections.Generic;
    using SME.VHDL;
    using SME.AST;
    using System;
    
    
    public partial class Entity : EntityBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 9 ""
            this.Write("library IEEE;\nuse IEEE.STD_LOGIC_1164.ALL;\nuse IEEE.NUMERIC_STD.ALL;\n\n-- library " +
                    "SYSTEM_TYPES;\nuse work.SYSTEM_TYPES.ALL;\n\n-- library CUSTOM_TYPES;\nuse work.CUST" +
                    "OM_TYPES.ALL;\n\n");
            
            #line default
            #line hidden
            
            #line 19 ""
 if (RSP.IsComponent) { 
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write("  -- Component declaration and signals\n");
            
            #line default
            #line hidden
            
            #line 21 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RSP.ComponentInclude ));
            
            #line default
            #line hidden
            
            #line 21 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 22 ""
 } 
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write("\n-- User defined packages here\n-- #### USER-DATA-IMPORTS-START\n-- #### USER-DATA-" +
                    "IMPORTS-END\n\n\nentity ");
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Process.Name ));
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write(" is\n  port(\n");
            
            #line default
            #line hidden
            
            #line 31 ""
 foreach (var bus in Process.InputBusses.Where(x => !Process.OutputBusses.Contains(x))) { 
       var busname = RS.GetLocalBusName(bus, Process);

            
            #line default
            #line hidden
            
            #line 34 ""
            this.Write("    -- Input bus ");
            
            #line default
            #line hidden
            
            #line 34 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( busname ));
            
            #line default
            #line hidden
            
            #line 34 ""
            this.Write(" signals\n");
            
            #line default
            #line hidden
            
            #line 35 ""
     foreach (var signal in bus.Signals) { 
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName(busname + "_" + signal.Name) ));
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write(": in ");
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 37 ""
     } 
            
            #line default
            #line hidden
            
            #line 38 ""
 } 
            
            #line default
            #line hidden
            
            #line 39 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 40 ""
 foreach (var bus in Process.OutputBusses.Where(x => !Process.InputBusses.Contains(x))) {
       var busname = RS.GetLocalBusName(bus, Process);

            
            #line default
            #line hidden
            
            #line 43 ""
            this.Write("    -- Output bus ");
            
            #line default
            #line hidden
            
            #line 43 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( busname ));
            
            #line default
            #line hidden
            
            #line 43 ""
            this.Write(" signals\n");
            
            #line default
            #line hidden
            
            #line 44 ""
     foreach (var signal in RSP.WrittenSignals(bus)) { 
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName(busname + "_" + signal.Name) ));
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write(": out ");
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 46 ""
     } 
            
            #line default
            #line hidden
            
            #line 47 ""
 } 
            
            #line default
            #line hidden
            
            #line 48 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 49 ""
 foreach (var bus in Process.InputBusses.Where(x => Process.OutputBusses.Contains(x))) {
       var busname = RS.GetLocalBusName(bus, Process);

            
            #line default
            #line hidden
            
            #line 52 ""
            this.Write("    -- Input/output bus ");
            
            #line default
            #line hidden
            
            #line 52 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( busname ));
            
            #line default
            #line hidden
            
            #line 52 ""
            this.Write(" signals\n");
            
            #line default
            #line hidden
            
            #line 53 ""
     foreach (var signal in bus.Signals) { 
            
            #line default
            #line hidden
            
            #line 54 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 54 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName(busname + "_" + signal.Name) ));
            
            #line default
            #line hidden
            
            #line 54 ""
            this.Write(": in ");
            
            #line default
            #line hidden
            
            #line 54 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 54 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 55 ""
     } 
            
            #line default
            #line hidden
            
            #line 56 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 57 ""
     foreach (var signal in bus.Signals) { 
            
            #line default
            #line hidden
            
            #line 58 ""
            this.Write("    out_");
            
            #line default
            #line hidden
            
            #line 58 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName(busname + "_" + signal.Name) ));
            
            #line default
            #line hidden
            
            #line 58 ""
            this.Write(": out ");
            
            #line default
            #line hidden
            
            #line 58 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 58 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 59 ""
     } 
            
            #line default
            #line hidden
            
            #line 60 ""
 } 
            
            #line default
            #line hidden
            
            #line 61 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 62 ""
 if (Process.SharedVariables.Any() || Process.SharedSignals.Any()) { 
            
            #line default
            #line hidden
            
            #line 63 ""
            this.Write("    -- Initialization values\n");
            
            #line default
            #line hidden
            
            #line 64 ""
     foreach (var variable in Process.SharedVariables) { 
            
            #line default
            #line hidden
            
            #line 65 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 65 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName("reset_" + variable.Name) ));
            
            #line default
            #line hidden
            
            #line 65 ""
            this.Write(": in ");
            
            #line default
            #line hidden
            
            #line 65 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(variable) ));
            
            #line default
            #line hidden
            
            #line 65 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 66 ""
     } 
            
            #line default
            #line hidden
            
            #line 67 ""
     foreach (var variable in Process.SharedSignals) { 
            
            #line default
            #line hidden
            
            #line 68 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 68 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName("reset_" + variable.Name) ));
            
            #line default
            #line hidden
            
            #line 68 ""
            this.Write(": in ");
            
            #line default
            #line hidden
            
            #line 68 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(variable) ));
            
            #line default
            #line hidden
            
            #line 68 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 69 ""
     } 
            
            #line default
            #line hidden
            
            #line 70 ""
 } 
            
            #line default
            #line hidden
            
            #line 71 ""
            this.Write("\n    -- Clock signal\n    CLK : in Std_logic;\n\n    -- Ready signal\n    RDY : in St" +
                    "d_logic;\n\n    -- Finished signal\n    FIN : out Std_logic;\n\n    -- Reset signal\n " +
                    "   RST : in Std_logic\n );\nend ");
            
            #line default
            #line hidden
            
            #line 84 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Process.Name ));
            
            #line default
            #line hidden
            
            #line 84 ""
            this.Write(";\n\narchitecture RTL of ");
            
            #line default
            #line hidden
            
            #line 86 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Process.Name ));
            
            #line default
            #line hidden
            
            #line 86 ""
            this.Write(" is\n");
            
            #line default
            #line hidden
            
            #line 87 ""
 foreach (var bus in Process.InternalBusses) {
       var busname = RS.GetLocalBusName(bus, Process);

            
            #line default
            #line hidden
            
            #line 90 ""
            this.Write("  -- Internal bus ");
            
            #line default
            #line hidden
            
            #line 90 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( busname ));
            
            #line default
            #line hidden
            
            #line 90 ""
            this.Write(" signals\n");
            
            #line default
            #line hidden
            
            #line 91 ""
     foreach (var signal in bus.Signals) { 
            
            #line default
            #line hidden
            
            #line 92 ""
            this.Write("  signal ");
            
            #line default
            #line hidden
            
            #line 92 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName(busname + "_" + signal.Name) ));
            
            #line default
            #line hidden
            
            #line 92 ""
            this.Write(": ");
            
            #line default
            #line hidden
            
            #line 92 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(signal) ));
            
            #line default
            #line hidden
            
            #line 92 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 93 ""
     } 
            
            #line default
            #line hidden
            
            #line 94 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 95 ""
 } 
            
            #line default
            #line hidden
            
            #line 96 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 97 ""
 if (Process.SharedSignals.Any()) { 
            
            #line default
            #line hidden
            
            #line 98 ""
            this.Write("  -- Internal signals\n");
            
            #line default
            #line hidden
            
            #line 99 ""
     foreach (var s in Process.SharedSignals) { 
            
            #line default
            #line hidden
            
            #line 100 ""
            this.Write("  signal ");
            
            #line default
            #line hidden
            
            #line 100 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( s.Name ));
            
            #line default
            #line hidden
            
            #line 100 ""
            this.Write(" : ");
            
            #line default
            #line hidden
            
            #line 100 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(s) ));
            
            #line default
            #line hidden
            
            #line 100 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 101 ""
     } 
            
            #line default
            #line hidden
            
            #line 102 ""
 } 
            
            #line default
            #line hidden
            
            #line 103 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 104 ""
 if (RSP.IsComponent) { 
            
            #line default
            #line hidden
            
            #line 105 ""
            this.Write("  -- Component declaration and signals\n");
            
            #line default
            #line hidden
            
            #line 106 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RSP.ComponentSignals ));
            
            #line default
            #line hidden
            
            #line 106 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 107 ""
 } 
            
            #line default
            #line hidden
            
            #line 108 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 109 ""
 if (Process.Methods != null && Process.Methods.Any(x => !x.Ignore)) { 
            
            #line default
            #line hidden
            
            #line 110 ""
            this.Write("  -- Internal methods\n");
            
            #line default
            #line hidden
            
            #line 111 ""
     foreach (var s in Process.Methods.Where(x => !x.Ignore)) { 
            
            #line default
            #line hidden
            
            #line 112 ""
         foreach(var line in RSP.Helper.RenderMethod(s)) { 
            
            #line default
            #line hidden
            
            #line 113 ""
            this.Write("  ");
            
            #line default
            #line hidden
            
            #line 113 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( line ));
            
            #line default
            #line hidden
            
            #line 113 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 114 ""
         } 
            
            #line default
            #line hidden
            
            #line 115 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 116 ""
     } 
            
            #line default
            #line hidden
            
            #line 117 ""
 } 
            
            #line default
            #line hidden
            
            #line 118 ""
            this.Write("\n\n  -- User defined signals, procedures and components here\n  -- #### USER-DATA-S" +
                    "IGNALS-START\n  -- #### USER-DATA-SIGNALS-END\n\nbegin\n\n    -- Custom processes go " +
                    "here\n    -- #### USER-DATA-PROCESSES-START\n    -- #### USER-DATA-PROCESSES-END\n\n" +
                    "");
            
            #line default
            #line hidden
            
            #line 130 ""
 if (RSP.IsComponent) { 
            
            #line default
            #line hidden
            
            #line 131 ""
            this.Write("    -- Component instantiation\n");
            
            #line default
            #line hidden
            
            #line 132 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RSP.ComponentProcesses ));
            
            #line default
            #line hidden
            
            #line 132 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 133 ""
 } else { 
            
            #line default
            #line hidden
            
            #line 134 ""
            this.Write("\n    process(\n        -- Custom sensitivity signals here\n        -- #### USER-DAT" +
                    "A-SENSITIVITY-START\n        -- #### USER-DATA-SENSITIVITY-END\n        RDY,\n     " +
                    "   RST\n    )\n");
            
            #line default
            #line hidden
            
            #line 142 ""
         if (RSP.Variables.Count() > 0) { 
            
            #line default
            #line hidden
            
            #line 143 ""
            this.Write("    -- Internal variables\n");
            
            #line default
            #line hidden
            
            #line 144 ""
         } 
            
            #line default
            #line hidden
            
            #line 145 ""
         foreach(var s in RSP.Variables) { 
            
            #line default
            #line hidden
            
            #line 146 ""
            this.Write("    variable ");
            
            #line default
            #line hidden
            
            #line 146 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( s.Name ));
            
            #line default
            #line hidden
            
            #line 146 ""
            this.Write(" : ");
            
            #line default
            #line hidden
            
            #line 146 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( RS.VHDLWrappedTypeName(s) ));
            
            #line default
            #line hidden
            
            #line 146 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 147 ""
         } 
            
            #line default
            #line hidden
            
            #line 148 ""
            this.Write(@"
    variable reentry_guard : Std_logic;

    -- #### USER-DATA-NONCLOCKEDVARIABLES-START
    -- #### USER-DATA-NONCLOCKEDVARIABLES-END
	begin
        -- Initialize code here
        -- #### USER-DATA-NONCLOCKEDSHAREDINITIALIZECODE-START
        -- #### USER-DATA-NONCLOCKEDSHAREDINITIALIZECODE-END

        if RST = '1' then
");
            
            #line default
            #line hidden
            
            #line 159 ""
     foreach(var s in RSP.ProcessResetStaments) { 
            
            #line default
            #line hidden
            
            #line 160 ""
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 160 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( s ));
            
            #line default
            #line hidden
            
            #line 160 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 161 ""
     } 
            
            #line default
            #line hidden
            
            #line 162 ""
     foreach(var variable in Process.SharedVariables) { 
            
            #line default
            #line hidden
            
            #line 163 ""
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 163 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( variable.Name ));
            
            #line default
            #line hidden
            
            #line 163 ""
            this.Write(" := ");
            
            #line default
            #line hidden
            
            #line 163 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName("reset_" + variable.Name) ));
            
            #line default
            #line hidden
            
            #line 163 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 164 ""
     } 
            
            #line default
            #line hidden
            
            #line 165 ""
     foreach(var variable in Process.SharedSignals) { 
            
            #line default
            #line hidden
            
            #line 166 ""
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 166 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( variable.Name ));
            
            #line default
            #line hidden
            
            #line 166 ""
            this.Write(" <= ");
            
            #line default
            #line hidden
            
            #line 166 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Naming.ToValidName("reset_" + variable.Name) ));
            
            #line default
            #line hidden
            
            #line 166 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 167 ""
     } 
            
            #line default
            #line hidden
            
            #line 168 ""
            this.Write(@"
            reentry_guard := '0';
            FIN <= '0';

            -- Initialize code here
            -- #### USER-DATA-NONCLOCKEDRESETCODE-START
            -- #### USER-DATA-NONCLOCKEDRESETCODE-END

        elsif RDY /= reentry_guard then

                reentry_guard := RDY;

                -- Initialize code here
                -- #### USER-DATA-NONCLOCKEDINITIALIZECODE-START
                -- #### USER-DATA-NONCLOCKEDINITIALIZECODE-END


");
            
            #line default
            #line hidden
            
            #line 185 ""
     foreach(var line in RSP.Helper.RenderMethod(Process.MainMethod)) { 
            
            #line default
            #line hidden
            
            #line 186 ""
            this.Write("                ");
            
            #line default
            #line hidden
            
            #line 186 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( line ));
            
            #line default
            #line hidden
            
            #line 186 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 187 ""
     } 
            
            #line default
            #line hidden
            
            #line 188 ""
            this.Write("\n                FIN <= RDY;\n\n        end if;\n\n        -- Non-clocked process act" +
                    "ions here\n\n        -- #### USER-DATA-CODE-START\n        -- #### USER-DATA-CODE-E" +
                    "ND\n\n    end process;\n");
            
            #line default
            #line hidden
            
            #line 199 ""
 } 
            
            #line default
            #line hidden
            
            #line 200 ""
            this.Write("\nend RTL;\n\n-- User defined architectures here\n-- #### USER-DATA-ARCH-START\n-- ###" +
                    "# USER-DATA-ARCH-END\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class EntityBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
